name: utopia_http_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <4.0.0'

dependencies:
  shelf:
  utopia_http:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
