name: utopia_framework
description: A light and easy to get started with HTTP framework for Dart
version: 0.0.1
homepage: https://github.com/utopia-dart/utopia_framework

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  mime: ^1.0.4
  http_parser: ^4.0.2
  string_scanner: ^1.2.0
  shelf: ^1.4.0
  shelf_static: ^1.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
  http: ^0.13.5
