name: utopia_http
description: A light and easy to get started with HTTP server library for Dart
version: 0.1.0
homepage: https://github.com/utopia-dart/utopia_http

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  mime: ^1.0.5
  http_parser: ^4.0.2
  string_scanner: ^1.2.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  utopia_di: ^0.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  http: ^1.2.1
